### ISSUE TITLE
Dateiendungen einblenden

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/windows-clients-todo-list#10]
Windows blendet standardmäßig Dateiendungen aus. Das ist aber total wichtig zu sehen. Dafür brauchen wir eine GPO.

**Comment by gurkih** [comment]
Sehen wir das tatsaechlich so? Gefuehlt ist die Meinung hierzu im Schnitt 60:40 fuer ausblenden

**Comment by vale** [comment]
Wir sollten wirklich Dateiendungen einblenden. Ausgeblendete Dateiendungen machen nur Probleme.

**Comment by Virtex7** [comment]
+1 für Dateiendungen.

"60:40 für ausblenden.." freilich, ausgedachte Statistik, mehr nicht.

**Comment by sedrubal** [comment]
Verbessere mich, wenn ich falsch liege, aber es gibt genau keinen Grund, Dateiendungen auszublenden. Sich auf die icons zu verlassen, die der Windows den Dateien gibt, ist grob fahrlässig.

**Comment by gurkih** [comment]
Da steht gefuehlt. Damit sage ich bereits dass das keine belastbare Zahl ist. Mir ist nicht ganz klar was genau jetzt dein Problem darstellt :p

Ich hab keine rechte Meinung dazu ob wir die einblenden wollen oder nicht, d.h. wenn das signifikant Leute tun wollen tun wir das einfach :-)

**Comment by gurkih** [comment]
erledigt.
