### ISSUE TITLE
VisiCut PlugIn für Inkscape installieren

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/windows-clients-todo-list#3]
Es wird sich irgendwie darauf belaufen, die [`*.py` und `*.inx` Dateien von hier](https://github.com/t-oster/VisiCut/tree/develop/tools/inkscape_extension) an die richtige Stelle zu schieben. Bei Linux ist es `/usr/share/inkscape/extensions/`, bei Windows weis ich es nicht.

**Comment by mgmax** [comment]
Bei Windows ziemlich sicher in Programme/Inkscape/extensions. Es kann sein, dass der VisiCut Setup das schon automatisch macht. Wenn nicht, wäre das ein guter Feature request, den man recht bequem umsetzen kann.

**Comment by sedrubal** [comment]
Gibt es ein setup für VisiCut unter Windows? Das kenne ich gar nicht...

**Comment by gurkih** [comment]
Wir muessten hierfuer zunaechst das Inkscapeproblem loesen - Inkscape + Mehrbenutzersystem = Schmerz.

Soll heissen: Inkscape legt fuer jeden Nutzer alles einzeln nochmals an, und ich schaffe es gerade nicht, ihm das passend hinzulegen. Das ist auch der Grund warum Inkscape 5 Minuten startet ...

**Comment by mgmax** [comment]
Also, das Inkscapeproblem ist eine Geschichte, die vollkommen unabhängig vom Visicut Plugin ist, und daher auch in eine extra Aufgabe sollte.
Um das Plugin zu installieren, einfach die von Basti erwähnten Dateien in den Ordner "extensions" kopieren, der irgendwo unterhalb von Programme\Inkscape\ liegt.

**Comment by mgmax** [comment]
erledigt:  [`*.py` und `*.inx` Dateien von hier](https://github.com/t-oster/VisiCut/tree/develop/tools/inkscape_extension)  nach C:\Programme\inkscape\share\extensions kopiert.

**Comment by sedrubal** [comment]
Wie konntest du das tun? Müssen die 2 Dateien nicht in einer Freigabe liegen und dann über eine Gruppenrichtlinie rein kopiert werden?

**Comment by mgmax** [comment]
Nein, das plugin ist systemweit nach C:/Programme/... installiert. So muss auch nicht jeder Nutzer einzeln aktualisieren

**Comment by gurkih** [comment]
Da gabs wohl ein Misverständnis. Der lokale Programmordner ist aber definitiv der schönere Wohnort :-)
