### ISSUE TITLE
Bildschirmsperre

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/windows-clients-todo-list#4]
Wie in #1 diskutiert, sollte eine automatische Passwortsperre nach wenigen Minuten aktiv werden. Außer ggf. für die Schulungskonten.

Das geht per GPO so: http://serverfault.com/a/741504

**Comment by arwarw** [comment]
Dagegen fuer alle Rechner, die Geraete steuern. Am einfachsten generell einfach nicht machen, weil sonst evtl die Einstellung im Benutzerprofil gespeichert ist und auf allen moeglichen Kisten aktiv wird (fuer den Benutzer) weil der vorher mal an einer Kiste eingeloggt war, die das erzwungen hat.

Alternativ einfach Steuerrechner nicht ins AD.

**Comment by Virtex7** [comment]
+1

Zudem: Streichung des Wortes "Alternativ" im zweiten Absatz.
so lange das so läuft wie ein Sack Nüsse (z.b. Zertifikatsfehler aktuell) halte ich es für unsinnig und gefährlich, einen Steuerrechner in die AD aufzunehmen.

**Comment by mgmax** [comment]
Fräsensteuerrechner definitiv nicht ins AD, denn die grandiose Software braucht Admin-Rechte.

**Comment by mgmax** [comment]
arw, welche Steuerrechner meinst du sonst? Drehbank ist ohnehin Linux und damit außen vor. Bei Plotter und 3D-Drucker sollte es nicht stören, weil man eh nicht interaktiv eingreifen kann.

**Comment by arwarw** [comment]
ich meinte CNC-Fraese, aber k.A. ob der dann Linux oder Windows wird. Fuer den Rest isses evtl egal.

**Comment by gurkih** [comment]
Zurzeit ist nicht geplant den Fraesenrechner in die AD zu nehmen. Aendert sich moeglicherweise irgendwann [tm], aber definitiv nicht zeitnah.

**Comment by gurkih** [comment]
sind mit der Anfrage die clients oder der lokale login an der ws11 gemeint?

**Comment by gurkih** [comment]
GPO ist auf den Clients aktiv. Die brauchen vermutlich nen Restart um die Richtlinie anzuwenden weil die aus der Computerkonfiguration stammt.

**Comment by mgmax** [comment]
dann schließe ich mal diese Aufgabe. Wenn es doch nicht funktioniert, kann mans ja wieder aufmachen.
