### ISSUE TITLE
Epilog ZING Windows Treiber Profile holen

### ISSUE THREAD

**Issue by Balagrio** [fau-fablab/windows-clients-todo-list#5]
sollten auch automatisch geladen werden, momentan liegen diese im Share und müssen bei jedem Neuankömmling eingerichtet werden

**Comment by gurkih** [comment]
Eigentlich gabs da ne Gruppenrichtlinie zu die das Leuten passend eingebunden hat ... ich schau mal was da kaputtgegangen ist

**Comment by gurkih** [comment]
Der Lasertreiber war aus nicht ganz klaren Gründen lokal installiert. Die RDP-Weiterleitung desselbigen sorgte für Verwirrung.
